SELECT THR.ID FROM ECOLI_DATA AS THR
INNER JOIN
(
    SELECT SEC.PARENT_ID, SEC.ID FROM ECOLI_DATA AS SEC
    INNER JOIN
    (
        SELECT FIR.ID FROM ECOLI_DATA AS FIR
        WHERE PARENT_ID IS NULL
    ) AS FIR
    ON SEC.PARENT_ID = FIR.ID
) AS SEC
ON THR.PARENT_ID = SEC.ID


