SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(MIN(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100)) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE LIKE '30%') AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND NOT EXISTS(
SELECT 1
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
  WHERE H.CAR_ID = C.CAR_ID
    AND NOT (
      H.END_DATE < '2022-11-01'
      OR H.START_DATE > '2022-11-30'
    ))
AND FLOOR(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) >= 500000
AND FLOOR(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) < 2000000
GROUP BY C.CAR_ID
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC