WITH AI AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AS AO
INNER JOIN AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AO.SEX_UPON_OUTCOME LIKE 'Spayed%'
OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY AO.ANIMAL_ID ASC