WITH FO AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
)
SELECT FD.PRODUCT_ID, FD.PRODUCT_NAME, FD.PRICE*FO.TOTAL AS TOTAL_SALES FROM FOOD_PRODUCT AS FD
INNER JOIN FO
ON FD.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

