WITH J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
)
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF
JOIN J
ON FIRST_HALF.FLAVOR = J.FLAVOR
GROUP BY FIRST_HALF.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER+J.TOTAL DESC
LIMIT 3

