WITH SK AS (
    SELECT CODE FROM SKILLCODES
    WHERE CATEGORY LIKE 'Front%'
)
SELECT DE.ID, DE.EMAIL, DE.FIRST_NAME, DE.LAST_NAME FROM DEVELOPERS AS DE
INNER JOIN SK
ON (DE.SKILL_CODE & SK.CODE) = SK.CODE
GROUP BY DE.ID, DE.EMAIL, DE.FIRST_NAME, DE.LAST_NAME
ORDER BY DE.ID ASC