WITH U AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE USED_GOODS_BOARD.STATUS LIKE "DONE%"
    GROUP BY WRITER_ID, USED_GOODS_BOARD.STATUS
    HAVING SUM(PRICE) >= 700000
)
SELECT UU.USER_ID, UU.NICKNAME, U.TOTAL_SALES
FROM USED_GOODS_USER AS UU
INNER JOIN U
ON UU.USER_ID = U.WRITER_ID
ORDER BY U.TOTAL_SALES ASC