WITH R AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
),
RR AS (
    SELECT REST_REVIEW.MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    INNER JOIN R
    ON REST_REVIEW.MEMBER_ID = R.MEMBER_ID
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') FROM MEMBER_PROFILE AS MP
INNER JOIN RR
ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC
