WITH CH AS (
    SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    WHERE H.START_DATE >= '2022-08-01'
    AND H.START_DATE <= '2022-10-31'
    GROUP BY H.CAR_ID
    HAVING COUNT(H.CAR_ID) >=5
)
SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(H.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
INNER JOIN CH
ON H.CAR_ID = CH.CAR_ID
WHERE H.START_DATE >= '2022-08-01'
AND H.START_DATE <= '2022-10-31'
GROUP BY MONTH, H.CAR_ID
HAVING COUNT(H.CAR_ID) > 0
ORDER BY MONTH ASC, H.CAR_ID DESC

