SELECT FI.ID, FN.FISH_NAME, FI.LENGTH AS LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM FISH_INFO
) AS FI
INNER JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.RN = 1
ORDER BY FI.ID ASC
