SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, CAST(ROUND(S/C, 0) AS UNSIGNED) AS AVG_SAL
FROM (
    SELECT DEPT_ID, SUM(SAL) AS S, COUNT(DEPT_ID) AS C
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS HE
INNER JOIN HR_DEPARTMENT AS HD
ON HE.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC